version: "3.8"

services:
  # === PostgreSQL ===
  postgres:
    image: postgres:15
    container_name: postgres_bot
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # === Bot Discord ===
  bot:
    image: bot_discord
    container_name: bot_discord
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=botuser
      - DB_PASSWORD=botpass
      - DB_NAME=botdb
    depends_on:
      - postgres

volumes:
  pgdata:
